kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mini-app
  labels:
    app: mini-app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mini-app
  template:
    metadata:
      labels:
        app: mini-app
    spec:
      containers:
        - name: mini-app
          image: mini-app
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
